Include other drivers from scikit-rf
pyvisa/pyvisa-drivers pull request #4
Opened 2019-06-25 18:29 UTC by trottmpq

Added the other two drivers from scikit-rf. added a generic instrument class to expand into other instrument classes as well.

2019-06-26 14:17 UTC, dvincentwest requested changes
First, thanks so much for putting the time into this.  You are the first person other than me to submit code here and I have been inactive on it for quite some time, so thank you.

After looking over your code there are a few major points to address:

1. keep all of your code contributions within the `drivers/vna` sub directory.
2. please rename it to vna_skrf since they are drivers fashioned via the skrf implementation, and other people may (someday) wish to submit vna drivers written in a completely different fashion
3. remove the pipenv files please
4. please do not include the abcinstr file

The main intention of this repository was for people to put their instrument code up without regard to a cohesive vision of how instrument drivers should be written.  It hasn't really taken off... but I haven't put a lot of effort into advertising it either.  Nonetheless, the aim is that each directory within drivers should be entirely separate from the others, not tied to a particular template, vision or dependency.

I am quite pleased to bring in the drivers here.  However, since you have put in some significant effort into writing templates for scikit-rf based vna drivers, I would also encourage you to consider contributing your template/class/design oriented efforts to that repository.

2019-06-26 18:41 UTC, trottmpq commented
Thanks for the feedback. I think I have made all the changes requested. I will hopefully get a few more pushed when I have some time.

2019-06-27 13:27 UTC, dvincentwest reviewed
Just one more thing to change which is that the README.md for the drivers directory should not contain any instructions about SCPI instruments, again for the reason posted previously.  I have looked over everything else, so when you move that I will merge the PR.  Thanks again

2019-06-27 13:27 UTC, dvincentwest commented on drivers/README.md
> +# Creating A Driver
This section is specific to SCPI drivers and should be included in the vna_skrf directory

2019-06-28 14:29 UTC, merged